export const projects = [
  {
    id: 'bazarr',
    title: 'Bazarr',
    tagline: 'Full-Stack E-Commerce Platform',
    status: 'In Development',
    statusType: 'wip',
    year: '2025',
    problem: 'Most e-commerce platforms sacrifice performance for features. Bazarr is engineered production-ready from day one — optimised MongoDB queries, secure PayPal flows, zero cross-browser regressions.',
    tech: ['Node.js', 'Express.js', 'React.js', 'MongoDB', 'PayPal API', 'JWT'],
    features: [
      'RESTful APIs for product management, auth & order processing',
      'PayPal gateway with secure token validation — 99%+ success rate across 50+ transactions',
      '15+ REST endpoints with cross-browser test suite (Chrome, Firefox, Safari)',
      'MongoDB compound indexing cutting API response time by 40% under peak load',
      'AI-powered virtual try-on allowing users to visualize outfits on their uploaded images',
      'AI-based outfit recommendation system generating complete looks from user prompts (event, style, preferences)',
      'Intelligent product matching using AI to combine items from database into cohesive outfits',
      'Admin panel for product, order and user management',
    ],
    challenge: 'Peak-load performance was the core challenge. Designed compound MongoDB indexes and query projection to cut response latency by 40%. Implemented idempotency keys in PayPal integration to prevent duplicate charges under network retries.',
    systemDesign: 'RESTful architecture with clear separation across routes, controllers and models. MongoDB for flexible product schema with embedded variant subdocuments. JWT stateless auth with refresh token rotation.',
    metrics: [
      { value: '40%', label: 'API Response Improvement' },
      { value: '99%+', label: 'Payment Success Rate' },
      { value: '15+', label: 'Endpoints Designed' },
    ],
    media: [
      { type: 'video', src: '/images/bazarr-demo.mp4' },
      { type: 'image', src: '/images/bazarr-1.png' },
      { type: 'image', src: '/images/bazarr-2.png' },
      { type: 'image', src: '/images/bazarr-3.png' },
      { type: 'image', src: '/images/bazarr-4.png' },
    ],
    demo: '#',
    github: '#',
    accentColor: '#0f3460',
  },
  {
    id: 'interviewly',
    title: 'Interviewly',
    tagline: 'AI-Powered Interview Platform',
    status: 'In Development',
    statusType: 'wip',
    year: '2025',
    problem: 'Interview prep is passive — you read, you watch, you forget. Interviewly simulates real interviews with an AI interviewer, analyses confidence and clarity in real-time, and gives data-driven feedback to close the gap between practice and getting hired.',
    tech: ['React.js', 'Node.js', 'jQuery', 'JavaScript', 'AI API', 'WebRTC', 'MongoDB'],
    features: [
      'AI interviewer "Aria" with real FAANG questions from Google, Amazon, Meta, Microsoft & Apple',
      'Real-time webcam analysis for confidence, eye contact and body language scoring',
      'Built-in coding IDE — Python, JavaScript, Java or C++ with test cases',
      'Anti-cheat monitor tracking tab-switches and camera-off events',
      'Post-session AI feedback report with charts and improvement roadmap',
      'Progress dashboard with AI mentor giving daily tasks to fix weak areas',
    ],
    challenge: 'Frontend re-render cycles were killing session performance. Used React DevTools profiler to pinpoint expensive component chains, applied useMemo and React.memo only where profiler confirmed overhead. Analysed session drop-offs from logs and redesigned mid-session UI — completion rates up 25%.',
    systemDesign: 'Event-driven session state machine managing phases (setup → live → review). AI feedback pipeline processes data asynchronously post-interview. WebRTC streams camera feed to a lightweight local analysis module.',
    metrics: [
      { value: '30%', label: 'Less Re-renders' },
      { value: '25%', label: 'Session Completion ↑' },
      { value: '6', label: 'Role Tracks' },
    ],
    media: [
      { type: 'video', src: '/images/interviewly-demo.mp4' },
      { type: 'image', src: '/images/interviewly-1.png' },
      { type: 'image', src: '/images/interviewly-2.png' },
      { type: 'image', src: '/images/interviewly-3.png' },
      { type: 'image', src: '/images/interviewly-4.png' },
    ],
    demo: '#',
    github: '#',
    accentColor: '#2d1b69',
  },
  {
    id: 'socialanalyzer',
    title: 'Social Media Analyzer',
    tagline: 'AI-Powered Content Analysis Tool',
    status: 'Completed',
    statusType: 'done',
    year: '2025',
    problem: 'Content creators publish blindly — no data on why one post performs and another dies. Upload any post as PDF or image, extract text via OCR, run it through AI, and get a full engagement scorecard with actionable improvements.',
    tech: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'AI API', 'OCR', 'PDF Parsing'],
    features: [
      'Drag-and-drop PDF upload with full text extraction, formatting preserved',
      'OCR processing for image-based posts and scanned documents',
      'AI-generated engagement score across 5 key metrics',
      'Actionable improvement suggestions from the AI analysis engine',
      'Full analysis history dashboard — track every upload and score over time',
      'Side-by-side comparison of original content vs AI-optimised version',
    ],
    challenge: 'OCR accuracy on low-resolution screenshots was inconsistent. Built a pre-processing pipeline normalising image contrast before OCR, significantly improving text extraction fidelity. PDF parsing required separate code paths for text-layer vs scanned-only documents.',
    systemDesign: 'Upload pipeline: file validation → type detection → parallel OCR/text-extraction → AI analysis → score aggregation → MongoDB. History queries use indexed userId + createdAt for O(log n) lookups.',
    metrics: [
      { value: '5', label: 'Engagement Metrics' },
      { value: 'PDF+IMG', label: 'Input Formats' },
      { value: 'Real-time', label: 'AI Analysis' },
    ],
    media: [
      { type: 'image', src: '/images/social-1.png' },
      { type: 'image', src: '/images/social-2.png' },
    ],
    demo: '#',
    github: '#',
    accentColor: '#4c1d95',
  },
]